#!/bin/bash

# To have video thumbnails show on opening the notebook (from code cell)
jupyter trust notebooks/*.ipynb

# needed both for notebook and lab environments
jupyter contrib nbextension install --user

# extensions for notebook
jupyter nbextension enable rubberband/main
jupyter nbextension enable exercise2/main
jupyter nbextension enable latex_envs/latex_envs
jupyter nbextension enable hide_input/main
jupyter nbextension enable toc2/main



# extensions for lab
jupyter nbextension enable --py widgetsnbextension
jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38
jupyter labextension install @osscar-org/jupyterlab-hide-code